name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      # Install pnpm
      - name: Install pnpm
        run: corepack enable

      # Install dependencies
      - name: Install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Run the build commands
      - name: Build .zip files
        run: |
          pnpm zip
          pnpm zip:firefox

      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Create a GitHub release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            This is the release for version ${{ env.VERSION }}.

      # Extract version from package.json
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      # Upload Chrome release asset
      - name: Upload Chrome release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .output/wechat-reader-enhancer-${{ steps.package-version.outputs.current-version }}-chrome.zip
          asset_name: wechat-reader-enhancer-${{ steps.package-version.outputs.current-version }}-chrome.zip
          asset_content_type: application/zip

      # Upload Firefox release asset
      - name: Upload Firefox release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .output/wechat-reader-enhancer-${{ steps.package-version.outputs.current-version }}-firefox.zip
          asset_name: wechat-reader-enhancer-${{ steps.package-version.outputs.current-version }}-firefox.zip
          asset_content_type: application/zip